# CyberShield: Cybersecurity Analytics & Threat Intelligence Platform

## Data Preprocessing and Exploratory Data Analysis

**Dataset:** UNSW-NB15

In [1]:
# =====================================
# STEP 1 : Import Required Libraries
# =====================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

## Step 2: Loading the Dataset

The official UNSW-NB15 training and testing datasets are loaded using the Pandas library.

In [2]:
train = pd.read_csv("../dataset/UNSW_NB15_training-set.csv")
test = pd.read_csv("../dataset/UNSW_NB15_testing-set.csv")

In [3]:
train.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.121478,tcp,-,FIN,6,4,258,172,74.087490,14158.9420,...,0,0,1,1,0,0,0,0,Normal,0
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473370,8395.1120,...,0,0,1,1,0,0,0,0,Normal,0
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,1572.2719,...,0,0,1,1,0,0,0,0,Normal,0
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,2740.1790,...,0,0,1,1,1,1,0,0,Normal,0
4,0.449454,tcp,-,FIN,10,6,534,268,33.373825,8561.4990,...,0,0,2,1,0,0,0,0,Normal,0

In [4]:
test.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.000011,udp,-,INT,2,0,496,0,90909.09,180363630.0,...,0,0,1,1,0,0,0,0,Normal,0
1,0.000008,udp,-,INT,2,0,1762,0,125000.00,881000000.0,...,0,0,1,1,0,0,0,0,Normal,0
2,0.000005,udp,-,INT,2,0,1068,0,200000.00,854400000.0,...,0,0,1,1,0,0,0,0,Normal,0
3,0.000006,udp,-,INT,2,0,900,0,166666.66,600000000.0,...,0,0,2,1,0,0,0,0,Normal,0
4,0.000010,udp,-,INT,2,0,2126,0,100000.00,850400000.0,...,0,0,2,1,0,0,0,0,Normal,0

## Step 4: Check Dataset Shape

In [5]:
print("Training Dataset Shape :", train.shape)
print("Testing Dataset Shape :", test.shape)

Training Dataset Shape : (175341, 36)
Testing Dataset Shape : (82332, 36)

## Step 5: Merge Training and Testing Dataset

In [6]:
data = pd.concat([train, test], ignore_index=True)

print("Merged Dataset Shape :", data.shape)

Merged Dataset Shape : (257673, 36)

## Step 6: Preview the Merged Dataset

In [7]:
data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.121478,tcp,-,FIN,6,4,258,172,74.087490,14158.9420,...,0,0,1,1,0,0,0,0,Normal,0
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473370,8395.1120,...,0,0,1,1,0,0,0,0,Normal,0
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,1572.2719,...,0,0,1,1,0,0,0,0,Normal,0
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,2740.1790,...,0,0,1,1,1,1,0,0,Normal,0
4,0.449454,tcp,-,FIN,10,6,534,268,33.373825,8561.4990,...,0,0,2,1,0,0,0,0,Normal,0

## Step 7: Dataset Information

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257673 entries, 0 to 257672
Data columns (total 36 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   dur                257673 non-null  float64
 1   proto              257673 non-null  object
 2   service            257673 non-null  object
 3   state              257673 non-null  object
 4   spkts              257673 non-null  int64
 5   dpkts              257673 non-null  int64
 6   sbytes             257673 non-null  int64
 7   dbytes             257673 non-null  int64
 8   rate               257673 non-null  float64
 9   sload              257673 non-null  float64
 10  dload              257673 non-null  float64
 11  sloss              257673 non-null  int64
 12  dloss              257673 non-null  int64
 13  sinpkt             257673 non-null  float64
 14  dinpkt             257673 non-null  float64
 15  sjit               257673 non-null  float64
 16  djit               257673 non-null  float64
 17  swin               257673 non-null  int64
 18  stcpb              257673 non-null  int64
 19  dtcpb              257673 non-null  int64
 20  dwin               257673 non-null  int64
 21  tcprtt             257673 non-null  float64
 22  synack             257673 non-null  float64
 23  ackdat             257673 non-null  float64
 24  smean              257673 non-null  int64
 25  dmean              257673 non-null  int64
 26  trans_depth        257673 non-null  int64
 27  response_body_len  257673 non-null  int64
 28  ct_src_dport_ltm   257673 non-null  int64
 29  ct_dst_sport_ltm   257673 non-null  int64
 30  is_ftp_login       257673 non-null  int64
 31  ct_ftp_cmd         257673 non-null  int64
 32  ct_flw_http_mthd   257673 non-null  int64
 33  is_sm_ips_ports    257673 non-null  int64
 34  attack_cat         257673 non-null  object
 35  label              257673 non-null  int64
dtypes: float64(11), int64(21), object(4)
memory usage: 70.8+ MB

## Step 8: Statistical Summary

In [9]:
# Generate statistical summary
data.describe()

,dur,spkts,dpkts,sbytes,dbytes,rate,sload,dload,sloss,dloss,...,dmean,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,label
count,257673.000000,257673.000000,257673.000000,2.576730e+05,2.576730e+05,257673.000000,2.576730e+05,2.576730e+05,257673.000000,257673.000000,...,257673.000000,257673.000000,2.576730e+05,257673.000000,257673.000000,257673.000000,257673.000000,257673.000000,257673.000000,257673.000000
mean,1.246715,19.777144,18.514703,8.572952e+03,1.438729e+04,91253.911040,7.060869e+07,6.582143e+05,4.889317,6.743691,...,121.649703,0.102242,1.968900e+03,5.238271,4.032677,0.012819,0.012850,0.132005,0.014274,0.639077
std,5.974305,135.947152,111.985965,1.737739e+05,1.461993e+05,160344.634259,1.857313e+08,2.412372e+06,65.574953,53.702222,...,254.041013,0.710593,4.962523e+04,8.160822,5.831515,0.116091,0.116421,0.681854,0.118618,0.480269
min,0.000000,1.000000,0.000000,2.400000e+01,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,30.789276,1.231800e+04,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.004285,4.000000,2.000000,5.280000e+02,1.780000e+02,2955.664800,7.439423e+05,1.747441e+03,0.000000,0.000000,...,44.000000,0.000000,0.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,0.685777,12.000000,10.000000,1.362000e+03,1.064000e+03,125000.000000,8.000000e+07,2.210538e+04,3.000000,2.000000,...,89.000000,0.000000,0.000000e+00,4.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,59.999990,10646.000000,11018.000000,1.435577e+07,1.465753e+07,1000000.000000,5.988000e+09,2.242273e+07,5319.000000,5507.000000,...,1500.000000,172.000000,6.558056e+06,59.000000,46.000000,4.000000,4.000000,30.000000,1.000000,1.000000

## Step 9: Display Column Names

In [10]:
# Display all column names
data.columns

Index(['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt',
       'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt',
       'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_src_dport_ltm', 'ct_dst_sport_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'is_sm_ips_ports',
       'attack_cat', 'label'],
      dtype='object')

## Step 10: Check Data Types

In [11]:
# Display data types
data.dtypes

dur                  float64
proto                 object
service               object
state                 object
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
is_sm_ips_ports        int64
attack_cat            object
label                  int64
dtype: object

# Data Preprocessing

## Step 11: Check Missing Values

In [12]:
# Count missing values in each column
data.isnull().sum()

dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
is_sm_ips_ports      0
attack_cat           0
label                0
dtype: int64

## Step 12: Duplicate Record Analysis

In [13]:
# Check duplicate records

duplicate_records = data.duplicated().sum()

print("Total Duplicate Records:", duplicate_records)

Total Duplicate Records: 112451

## Step 13: Investigate Duplicate Records

In [14]:
# Display the first few duplicate rows
duplicates = data[data.duplicated()]
duplicates.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
58,0.000000,arp,-,INT,1,0,46,0,0.000000,0.000000e+00,...,0,0,1,1,0,0,0,1,Normal,0
66,50.004400,ospf,-,INT,6,0,384,0,0.099991,5.119550e+01,...,0,0,1,2,0,0,0,0,Normal,0
169,0.000011,udp,-,INT,2,0,2120,0,90909.090000,7.709091e+08,...,0,0,7,2,0,0,0,0,Normal,0
214,0.001146,udp,dns,CON,2,2,146,178,2617.801000,5.095986e+05,...,0,0,2,2,0,0,0,0,Normal,0
313,0.001098,udp,dns,CON,2,2,132,164,2732.240500,4.808743e+05,...,0,0,3,2,0,0,0,0,Normal,0

In [15]:
# Display the shape of duplicate records
duplicates.shape

(112451, 36)

In [16]:
# Check duplicate percentage
duplicate_percentage = (duplicate_records / len(data)) * 100

print(f"Duplicate Percentage: {duplicate_percentage:.2f}%")

Duplicate Percentage: 43.64%

## Step 14: Remove Duplicate Records

In [17]:
# Remove duplicate records

data = data.drop_duplicates()

print("Dataset Shape After Removing Duplicates:", data.shape)

Dataset Shape After Removing Duplicates: (145222, 36)

In [18]:
# Verify duplicate removal

print("Remaining Duplicate Records:", data.duplicated().sum())

Remaining Duplicate Records: 0

## Step 15: Verify Dataset Shape After Cleaning

In [19]:
print("Final Dataset Shape:", data.shape)

Final Dataset Shape: (145222, 36)

## Step 16: Data Type Verification

In [20]:
# Check data types of all columns

data.dtypes

dur                  float64
proto                 object
service               object
state                 object
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
is_sm_ips_ports        int64
attack_cat            object
label                  int64
dtype: object

In [21]:
# Count different data types

data.dtypes.value_counts()

int64      21
float64    11
object      4
Name: count, dtype: int64

In [22]:
# Display categorical columns

categorical_columns = data.select_dtypes(include='object').columns

print("Categorical Columns:")

categorical_columns

Categorical Columns:

Index(['proto', 'service', 'state', 'attack_cat'], dtype='object')

In [23]:
# Display numerical columns

numerical_columns = data.select_dtypes(include=['int64','float64']).columns

print("Number of Numerical Columns:", len(numerical_columns))

numerical_columns

Number of Numerical Columns: 32

Index(['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sload', 'dload',
       'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb',
       'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean',
       'trans_depth', 'response_body_len', 'ct_src_dport_ltm',
       'ct_dst_sport_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd',
       'is_sm_ips_ports', 'label'],
      dtype='object')

## Step 17: Label Encoding of Categorical Features

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
label_encoder = LabelEncoder()

In [26]:
categorical_columns

Index(['proto', 'service', 'state', 'attack_cat'], dtype='object')

In [27]:
for column in categorical_columns:
    data[column] = label_encoder.fit_transform(data[column])

In [28]:
data.dtypes.value_counts()

int64      25
float64    11
Name: count, dtype: int64

In [29]:
data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.121478,113,0,4,6,4,258,172,74.087490,14158.9420,...,0,0,1,1,0,0,0,0,6,0
1,0.649902,113,0,4,14,38,734,42014,78.473370,8395.1120,...,0,0,1,1,0,0,0,0,6,0
2,1.623129,113,0,4,8,16,364,13186,14.170161,1572.2719,...,0,0,1,1,0,0,0,0,6,0
3,1.681642,113,3,4,12,12,628,770,13.677108,2740.1790,...,0,0,1,1,1,1,0,0,6,0
4,0.449454,113,0,4,10,6,534,268,33.373825,8561.4990,...,0,0,2,1,0,0,0,0,6,0

## Step 18: Feature Scaling (Standardization)

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
# Create StandardScaler object

scaler = StandardScaler()

In [32]:
# Create feature dataset by excluding target columns

features = data.drop(columns=['label', 'attack_cat'])

target = data[['label', 'attack_cat']]

In [33]:
# Scale only feature columns

scaled_features = pd.DataFrame(
    scaler.fit_transform(features),
    columns=features.columns
)

In [34]:
# Combine scaled features with target columns

processed_data = pd.concat(
    [scaled_features, target.reset_index(drop=True)],
    axis=1
)

In [35]:
processed_data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,label,attack_cat
0,-0.237501,0.106283,-0.671545,0.139017,-0.144480,-0.191702,-0.061763,-0.129779,-0.242915,-0.183584,...,-0.187214,-0.052332,-0.270001,-0.156656,-0.127731,-0.127711,-0.324106,-0.064626,0,6
1,-0.138246,0.106283,-0.671545,0.139017,-0.099670,0.041842,-0.059690,0.089099,-0.242862,-0.183615,...,-0.187214,-0.052332,-0.270001,-0.156656,-0.127731,-0.127711,-0.324106,-0.064626,0,6
2,0.044557,0.106283,-0.671545,0.139017,-0.133277,-0.109275,-0.061301,-0.061702,-0.243648,-0.183651,...,-0.187214,-0.052332,-0.270001,-0.156656,-0.127731,-0.127711,-0.324106,-0.064626,0,6
3,0.055547,0.106283,0.409479,0.139017,-0.110872,-0.136750,-0.060151,-0.126651,-0.243655,-0.183645,...,-0.187214,-0.052332,-0.270001,-0.156656,7.646503,7.629053,-0.324106,-0.064626,0,6
4,-0.175897,0.106283,-0.671545,0.139017,-0.122075,-0.177964,-0.060561,-0.129277,-0.243413,-0.183614,...,-0.187214,-0.052332,0.078134,-0.156656,-0.127731,-0.127711,-0.324106,-0.064626,0,6

In [36]:
processed_data.describe()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,label,attack_cat
count,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,...,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,1.452220e+05,145222.000000,145222.000000
mean,3.640246e-17,3.624589e-16,1.033360e-16,-1.557869e-16,7.045637e-18,8.611334e-18,2.348546e-18,-4.697092e-18,-1.409127e-17,-2.152834e-18,...,-6.849925e-18,-1.839694e-17,6.556357e-18,-4.227382e-17,-4.305667e-17,5.323370e-17,-6.262789e-18,1.604840e-17,0.449360,5.008428
std,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,...,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,1.000003e+00,0.497431,1.559969
min,-2.603186e-01,-7.940969e+00,-6.715451e-01,-4.863683e+00,-1.724856e-01,-2.191778e-01,-6.278216e-02,-1.306785e-01,-2.438219e-01,-1.836592e-01,...,-1.872141e-01,-5.233175e-02,-2.700008e-01,-1.566561e-01,-1.277308e-01,-1.277108e-01,-3.241055e-01,-6.462600e-02,0.000000,0.000000
25%,-2.568402e-01,1.062835e-01,-6.715451e-01,1.390175e-01,-1.332772e-01,-1.779641e-01,-6.043001e-02,-1.292766e-01,-2.435296e-01,-1.836166e-01,...,-1.872141e-01,-5.233175e-02,-2.700008e-01,-1.566561e-01,-1.277308e-01,-1.277108e-01,-3.241055e-01,-6.462600e-02,0.000000,4.000000
50%,-1.720007e-01,1.062835e-01,-6.715451e-01,1.390175e-01,-1.220748e-01,-1.642262e-01,-5.849603e-02,-1.271319e-01,-2.431153e-01,-1.834923e-01,...,-1.872141e-01,-5.233175e-02,-2.700008e-01,-1.566561e-01,-1.277308e-01,-1.277108e-01,-3.241055e-01,-6.462600e-02,0.000000,6.000000
75%,-7.006791e-02,1.062835e-01,7.698200e-01,1.390175e-01,-5.486045e-02,-8.179881e-02,-5.083848e-02,-1.135416e-01,-2.102660e-01,-1.804012e-01,...,-1.872141e-01,-5.233175e-02,-2.700008e-01,-1.566561e-01,-1.277308e-01,-1.277108e-01,-3.241055e-01,-6.462600e-02,1.000000,6.000000
max,1.100960e+01,1.459361e+00,3.652550e+00,7.643069e+00,5.945228e+01,7.546293e+01,6.246838e+01,7.654353e+01,1.199288e+01,3.167785e+01,...,1.845579e+02,9.942652e+01,1.992181e+01,3.086501e+01,3.096920e+01,3.089934e+01,5.002777e+01,1.547365e+01,1.000000,9.000000

## Step 19: Save Processed Dataset

In [37]:
import os

# Create output directory if it doesn't exist
os.makedirs("../output", exist_ok=True)

# Save processed dataset
processed_data.to_csv("../output/processed_dataset.csv", index=False)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.

# ==================================================
# Create Dataset for R Visualizations
# ==================================================

In [38]:
visualization_data = train.copy()

In [39]:
visualization_data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,attack_cat,label
0,0.121478,tcp,-,FIN,6,4,258,172,74.087490,14158.9420,...,0,0,1,1,0,0,0,0,Normal,0
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473370,8395.1120,...,0,0,1,1,0,0,0,0,Normal,0
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,1572.2719,...,0,0,1,1,0,0,0,0,Normal,0
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,2740.1790,...,0,0,1,1,1,1,0,0,Normal,0
4,0.449454,tcp,-,FIN,10,6,534,268,33.373825,8561.4990,...,0,0,2,1,0,0,0,0,Normal,0

In [40]:
import os

os.makedirs("../visualization", exist_ok=True)

visualization_data.to_csv(
    "../visualization/visualization_dataset.csv",
    index=False
)

print("Visualization dataset saved successfully.")

Visualization dataset saved successfully.